name: colors_notes
description: "Color your days"
publish_to: 'none'

version: 1.6.4+58

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Dépendances de l'application avec des versions corrigées et compatibles
  cloud_firestore: ^5.6.9
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.5.0
  firebase_auth: ^5.6.0
  firebase_auth_web: ^5.11.0
  firebase_core: ^3.14.0 # <-- Version corrigée
  flutter_colorpicker: ^1.1.0
  flutter_cookie_consent: ^1.0.2
  flutter_markdown_plus: ^1.0.3
  flutter_svg: ^2.1.0
  flutter_web_plugins:
    sdk: flutter
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  logger: ^2.3.0
  material_color_utilities: ^0.11.1
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.0.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  # Dépendances de test (déplacées et ajoutées ici)
  build_runner: ^2.4.8
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2

  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: "^0.14.4"


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/privacy_policy_fr.md
    - assets/privacy_policy_en.md
    - assets/privacy_policy_de.md
    - assets/privacy_policy_es.md
    - assets/privacy_policy_it.md
    - assets/privacy_policy_pt.md
    - assets/privacy_policy_pt_BR.md
    - LICENSE
    - assets/signin-assets/Web/svg/light/web_light_sq_na.svg

flutter_intl:
  enabled: true
